### ISSUE TITLE
xinterpreter should be responsible for using the history manager

### ISSUE THREAD

**Issue by martinRenou** [jupyter-xeus/xeus#101]
Right now, the `kernel` owns the `interpreter` and the `history manager`. If the `interpreter` owns the `history manager` and is responsible for using it, it brings more flexibility for xeus users, as they can easily create their own `history manager`, plug it to the `interpreter`, and use it the way they want.

**Comment by JohanMabille** [comment]
The way clients use the history manager and the lifetime of the history manager are orthogonal. The kernel needs to know th history manager so that it can route messages to it. I find it simpler and safer to delegate to the kernel lifetime of objects that it needs. Besides, if the default implementation of history manager is fine, I don't want to bother Jupyter Kernel authors with managing its lifetime.

A solution is to register the history manager in the interpreter (but without transfering ownership) so user can access it if they need. What use case did you have in mind that cannot be handled by the kernel?

**Comment by JohanMabille** [comment]
The `register_history_manager` method has been added to the interpreter API, and `xhistory_manager` can be inherited so that users can provide their own implementation.
