### ISSUE TITLE
Accessing server from kernel

### ISSUE THREAD

**Issue by lassoan** [jupyter-xeus/xeus#234]
We are doing finishing touches on 3D Slicer's xeus-python kernel integration and we would like to optimize interactive performance. For this, we need to tune communication parameters (poll timer, timeout) of the server at runtime and for this we would need a pointer to the server. We have a pointer to the kernel and to the interpreter, but there is no public API to access the server from those (p_server member is private in xkernel.hpp).

What solution would you recommend to access the current server instance?

**Comment by JohanMabille** [comment]
Is that something you can specify when instantiating the server? Or something you want to adapt during the lifetime of the server?

In the first case, we can add parameter to the `make_server` / `make_control_server` / `make_shell_server` methods. Otherwise, we can add a method to get the server form the kernel, and add methods to the server's API so that you can change these parameters.

**Comment by lassoan** [comment]
We would like to modify the data continuously. Adding a GetServer() method to the kernel would be enough, as we have subclassed our server and can add all the necessary custom methods there.

**Comment by lassoan** [comment]
Thank you, it works well!
